### ISSUE TITLE
OpenSSL default protocols changing for security reasons

### ISSUE THREAD

**Issue by headius** [jruby/jruby-openssl#12]
This bug details changes MRI will soon make to the default protocols/algorithms used in OpenSSL, specifically involving SSLv2 and v3: https://bugs.ruby-lang.org/issues/9424

We need to understand these changes and ensure jruby-openssl makes appropriate compatible changes if necessary.

**Comment by kares** [comment]
closing since **0.9.7** should be aligned with these
