### ISSUE TITLE
Few cipher suites on IBM JRE

### ISSUE THREAD

**Issue by ysohda** [jruby/jruby-openssl#125]
Hi all,

There are a few cipher suites on IBM JRE even though IBM JRE supports more ciphers.
Here are results of cipher suites on JRuby 9.1.8.0 with IBM JRE 8.0.4.1 (and Oracle JRE 1.8.0_121).

JRuby 9.1.8.0 IBM JRE 8.0.4.1 (/w unrestricted JCE policy)
>jruby  -e "require 'openssl'; ctx=OpenSSL::SSL::SSLContext.new; ctx.ciphers.each { |c| p c}"
["EXP-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]
["EXP-EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]
["EXP-EDH-DSS-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]
["DES-CBC-SHA", "TLSv1/SSLv3", 56, 56]
["EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 56, 56]

Oracle JDK 1.8.0_121 (/w unrestricted JCE policy)
>jruby  -e "require 'openssl'; ctx=OpenSSL::SSL::SSLContext.new; ctx.ciphers.each { |c| p c}"
["EXP-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]
["EXP-EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]
["EXP-EDH-DSS-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]
["DES-CBC-SHA", "TLSv1/SSLv3", 56, 56]
["EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 56, 56]
["ECDHE-ECDSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256]
["ECDHE-RSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256]
["ECDH-ECDSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256]
["ECDH-RSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256]
["ECDHE-ECDSA-AES128-SHA", "TLSv1/SSLv3", 128, 128]
["ECDHE-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128]
["AES128-SHA", "TLSv1/SSLv3", 128, 128]
["ECDH-ECDSA-AES128-SHA", "TLSv1/SSLv3", 128, 128]
["ECDH-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128]
["DHE-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128]
["DHE-DSS-AES128-SHA", "TLSv1/SSLv3", 128, 128]
["ECDHE-ECDSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["ECDHE-RSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["ECDH-ECDSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["ECDH-RSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["EDH-RSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["EDH-DSS-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]
["ECDHE-ECDSA-AES256-SHA", "TLSv1/SSLv3", 256, 256]
["ECDHE-RSA-AES256-SHA", "TLSv1/SSLv3", 256, 256]
["AES256-SHA", "TLSv1/SSLv3", 256, 256]
["ECDH-ECDSA-AES256-SHA", "TLSv1/SSLv3", 256, 256]
["ECDH-RSA-AES256-SHA", "TLSv1/SSLv3", 256, 256]
["DHE-RSA-AES256-SHA", "TLSv1/SSLv3", 256, 256]
["DHE-DSS-AES256-SHA", "TLSv1/SSLv3", 256, 256]

This occurs because of difference of cipher suite name prefix between Oracle JRE and IBM JRE.
When getting supported cipher suites on IBM JRE, the suite names start with "SSL_". On Oracle JRE, the suite names start with "TLS_".
Example:
IBM JRE:  SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Oracle JRE: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

As stated on https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/ciphersuites.html, IBM JRE supports more cipher suites and they also mentions:
> Note: In the following list, the string "SSL" is interchangeable with "TLS" and vice versa. For example, where SSL_RSA_WITH_AES_128_CBC_SHA is specified, TLS_RSA_WITH_AES_128_CBC_SHA also applies.

So, I think it is better to put additional mappings of cipher suites' strings to openssl algorithms for IBM JRE.

Thanks,
Yuki.

**Comment by ysohda** [comment]
I created a pull request #126 Add cipher suite strings for IBM JRE for this issue.

**Comment by kares** [comment]
resolved with https://github.com/jruby/jruby-openssl/pull/126

**Comment by keisukenitta** [comment]
Hi, @kares 

can i expect the next release (v0.9.21?) will contain the fix for this issue and will be released in the near future?
