### ISSUE TITLE
getting serial number from CRL list

### ISSUE THREAD

**Issue by Kavi6** [jruby/jruby-openssl#129]
I have a revoked.crl Certificate Revocation List with some entries. how to retrieve serial number from it. when i use revoked method, it return array of entries like  
"#<OpenSSL::X509::Revoked:0x007f944b1fd0d8>" . can anyone tell me how to parse this to get exact serial number?

**Comment by kares** [comment]
should be the same as for MRI, are you having JRuby issues with it that might be considered a bug ?
HINT: if not, use a ruby-forum or stack-overflow for questions such as these ... for better/quicker feedback.

**Comment by kares** [comment]
closing - seems that this was more of a q than a bug report for jruby-openssl
