### ISSUE TITLE
improve secure-random options

### ISSUE THREAD

**Issue by kares** [jruby/jruby-openssl#135]
with latest JOSSL updating BC to 1.56 `OpenSSL::Random` constantly feed itself from entropy-source

e.g. https://github.com/jruby/jruby/issues/4644

shall look into potential improvements with optional prop(s) and maybe even respect `-Xpreferred.prng=`

**Comment by headius** [comment]
Ugh.

**Comment by kares** [comment]
hopefully delivered in jruby-openssl 0.9.21 ... at least `-Xpreferred.prng` is now aligned and respected
