### ISSUE TITLE
Bad Subject Key Identifier Calc

### ISSUE THREAD

**Issue by i4s-aruiz** [jruby/jruby-openssl#153]
I think that there are an error in the calc of de Subject Key Identifier, it must be calculate with the subject PK not with the issuer PK, [RFC](https://tools.ietf.org/html/rfc5280#section-4.2.1.2), in this file [ExtensionFactory](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/X509ExtensionFactory.java), issuer Public Key is the only one being used(lines 436,423,553)

**Comment by kares** [comment]
thanks, was resolved in 0.10.4
