### ISSUE TITLE
gen_random_openssl missing

### ISSUE THREAD

**Issue by headius** [jruby/jruby-openssl#159]
I'm not sure when it was added, but apparently the openssl library should provide a method `gen_random_openssl` on SecureRandom, that then gets used as `gen_random` from then on.

The tests were modified to call the openssl version of the method in https://github.com/ruby/ruby/commit/782b2050b83

MRI's securerandom.rb has the logic to switch to the openssl version of `gen_random` here: https://github.com/ruby/ruby/blob/7ed3aae2feb91c584c5402dd6f63c145acd1f033/lib/securerandom.rb#L54-L79

JRuby's securerandom has differed for some time due to having a native component based on Java's RNGs.

**Comment by kares** [comment]
from what I read `gen_random_openssl` is an internal method to exist on `SecureRandom`
... all `OpenSSL::Random` methods are there. so I believe there's nothing to do here, mostly work for core.
believe its fine tagged as is for now `SecureRandom.gen_random_openssl(n)` is internal + the `SecureRandom` impl can handle its initialization just fine by being a wrapper around Java's SecureRandom
