### ISSUE TITLE
Unable to Add Path to Store

### ISSUE THREAD

**Issue by alsaha** [jruby/jruby-openssl#179]
Hi, 

I'm running "OpenSSL 1.0.2o  27 Mar 2018" and I'm unable to populate certificates into the key store from a specific folder.

    $store = OpenSSL::X509::Store.new
    $store.add_path("./certificates")
    client_cert = OpenSSL::X509::Certificate.new get_peer_cert
    raise "Certificate was not signed by the right authority." if !($store.verify(client_cert))

**Comment by kares** [comment]
closing this as defunct, we would have needed more details (not even sure what JRuby was used)
