### ISSUE TITLE
Failure to create and verify ECDSA signatures

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [jruby/jruby-openssl#193]
Haven't tested it with other algorithms, but attempting to generate a Digest-type signature using `secp256r1`/`P-256` (`ECDSA`) key using `SHA-1` hashing algorithm 

```
OpenSSL::PKey::EC.new(File.read('ecdsa.key')).sign(OpenSSL::Digest::SHA1.new, 'foobar')
```

fails with

```
OpenSSL::PKey::PKeyError: SHA1WITHEC Signature not available
    sign at org/jruby/ext/openssl/PKey.java:223
```

---

Cursory investigation brings me to [Bouncy Castle](https://github.com/rcoscali/external-bouncycastle/blob/master/bcprov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/EC.java#L67-L73), where `SHA1WITHECDSA` algo does exists.

I have cobbled up a hacky patch to pass `ECDSA` in around [here](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/PKey.java#L219) when `PKeyEC` instance is in play. It does work (both sign/verify output proper values, cross checked with CRuby's OpenSSL), but am not sure about architectural validity of this approach.

**Comment by kares** [comment]
Hey Aleks, that makes sense. The `EC` support wasn't completely polished.
But this [part should return](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/PKeyEC.java#L223) `"ECDSA"` ... as you already figured. Please fire up a PR.

**Comment by aleksandrs-ledovskis** [comment]
@kares As the 25972fd commit only contains test but not an implementation, and causes some CI failures, I think this issue in itself isn't fully resolved?
