### ISSUE TITLE
OpenSSL implementation doesn't support ALPN.

### ISSUE THREAD

**Issue by kvokka** [jruby/jruby-openssl#217]
In the process of starting [falcon](https://github.com/socketry/falcon) server got an error https://github.com/socketry/falcon/issues/135 which after @headius clarification appears to be in here (as a the missing feature)

**Comment by HoneyryderChuck** [comment]
[ALPN support just landed in Bouncy Castle 1.69](https://www.bouncycastle.org/latest_releases.html) (cc @headius )

**Comment by alexvelickiy** [comment]
+1 for support of ALPN

**Comment by headius** [comment]
🎉
