### ISSUE TITLE
SSL engine init causes unnecessary reverse DNS, slowing boot

### ISSUE THREAD

**Issue by headius** [jruby/jruby-openssl#22]
This is from http://jira.codehaus.org/browse/JRUBY-6891, reported by Ben Porterfield.

Original report
===========

Came across issue when a new client was getting ~10s delays before page loads. They were hitting an IP in their network that did not have reverse DNS name associated with it. Turned out that requests were being made by JRuby SSL to do reverse DNS lookup on the IP, and those requests were timing out before continuing with the request.
https://github.com/jruby/jruby/blob/master/src/org/jruby/ext/openssl/SSLSocket.java#L142 - this line will always force a reverse DNS lookup for an SSL connection.
http://docs.oracle.com/javase/1.5.0/docs/api/javax/net/ssl/SSLContext.html#createSSLEngine() - this documentation suggests that passing hostname and port should only be required for certain cipher suites.
Perhaps a flag to force the reverse lookup if you think it's required?
Additionally, there seems to be some potential issues in that SSLSocket is in no way associated with Ruby's Socket or BasicSocket...so, for example, a flag like BasicSocket.do_not_reverse_lookup will not be adhered to when using SSLSocket (See comment https://github.com/jruby/jruby/blob/master/src/org/jruby/ext/openssl/SSLSocket.java#L130, for example).

UPDATED relevant line numbers, currently are : 

https://github.com/jruby/jruby-openssl/blob/2e8cd57d32382289d5f6e6143027423301637f41/src/main/java/org/jruby/ext/openssl/SSLSocket.java#L162

https://github.com/jruby/jruby-openssl/blob/2e8cd57d32382289d5f6e6143027423301637f41/src/main/java/org/jruby/ext/openssl/SSLSocket.java#L144-L146

Additional follow-up
===============

My fix in jruby/jruby@d43177d40ee97ab91025db4eb1e4de03c5eb7a1f was attempted, but appeared to break behavior. See original report.

**Comment by kares** [comment]
from Patrick's comment: 
> If we assume that Ruby code that wants to use SNI always explicitly sets a hostname property within SSLSocket (not sure if that is valid assumption, but net/http seems to assume it) then we could explicitly check whether this member is a FQDN hostname (i.e. not an ip address) and call createSSLEngine with the appropriate hostname/port. If hostname is not set and/or it is an IP address, we call createSSLEngine with an empty argument list.

seems that we actually follow that logic exactly (at least in **0.9.6**): https://github.com/jruby/jruby-openssl/blob/2e8cd57d32382289d5f6e6143027423301637f41/src/main/java/org/jruby/ext/openssl/SSLContext.java#L615-L623
