### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by tuxmea** [jruby/jruby-openssl#227]
Latest release is version 0.10.5 from October 1st 2020.
Can we have a new release with all actual commits and fixes?

**Comment by rwaffen** [comment]
Hi,

I also would love to see a new release. I'm stuck on a problem with setting the iv_len and the commit adding this feature is not in a release right now :(

THX and Greeting, Robert

**Comment by tuxmea** [comment]
The fix for the comment from @rwaffen is in https://github.com/jruby/jruby-openssl/commit/79368fc6f4a0c19e2e05b99ab6532d6ace086ace
This commit was added on October 5th 2020.

**Comment by rwaffen** [comment]
@kares you did the last releases. is there anything we can do to have a new release?

**Comment by kares** [comment]
0.10.6 is out
