### ISSUE TITLE
EndOfContent has different ancestors than CRuby

### ISSUE THREAD

**Issue by headius** [jruby/jruby-openssl#228]
See https://github.com/sorbet/sorbet/issues/1216

The `EndOfContent` class has different ancestors than CRuby, which apparently causes trouble for Sorbet.

```
$ jruby -ropenssl -e "p OpenSSL::ASN1::EndOfContent.ancestors"
[OpenSSL::ASN1::EndOfContent, OpenSSL::ASN1::Primitive, OpenSSL::ASN1::ASN1Data, Object, Kernel, BasicObject]

$ ruby26 -ropenssl -e "p OpenSSL::ASN1::EndOfContent.ancestors"
[OpenSSL::ASN1::EndOfContent, OpenSSL::ASN1::ASN1Data, Object, Kernel, BasicObject]
```

**Comment by kares** [comment]
expected to be fixed with https://github.com/jruby/jruby-openssl/commit/def86097ad06c4423ffce5bb96a833e8a01ec7de (will be available in >= 0.13.0)
