### ISSUE TITLE
`OpenSSL::PKey::DH#q` is not implemented

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby-openssl#253]
While technically the `#p`. `#q`, and `#g` methods for [OpenSSL::PKey::DH](https://rubydoc.info/stdlib/openssl/OpenSSL/PKey/DH) are not documented, they are callable. However, jruby-openssl seems to lack the `#q` method.

## Steps To Reproduce

```ruby
dh = OpenSSL::PKey::DH.new(1024)
dh.q
```

## Expected Behavior

```ruby
# => #<OpenSSL::BN:...>
```

## Actual Result

```
NoMethodError (undefined method `q' for #<OpenSSL::PKey::DH:0x3eee08f5>)
```

## Version

* `jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM 11.0.15+10 on 11.0.15+10 +jit [linux-x86_64]`
* `jruby-openssl (default: 0.11.0 java)`

**Comment by peterbherman** [comment]
May be related to [this](https://github.com/ruby/openssl/commit/7ea72f1f50849ad0c36e08c0ac70bbdba1d96169#diff-c3543440d2bf902bef5b525645850a6477ee1ba82da1b7371295f2910320d744R178) change:

```
* ext/openssl/openssl_missing.[ch]: Implement EVP_PKEY_get0_*() and
  {RSA,DSA,EC_KEY,DH}_get0_*() functions.
  OpenSSL 1.1.0 makes EVP_PKEY/RSA/DSA/DH opaque. We used to provide
  setter methods for each parameter of each PKey type, for example
  PKey::RSA#e=, but this is no longer possible because the new API
  RSA_set0_key() requires the 'n' at the same time. This commit adds
  deprecation warning to them and adds PKey::*#set_* methods as direct
  wrapper for those new APIs. For example, 'rsa.e = 3' now needs to be
  rewritten as 'rsa.set_key(rsa.n, 3, rsa.d)'.
  [ruby-core:75225] [Feature #12324]
```

**Comment by kares** [comment]
added a dummy (`nil`) q at: https://github.com/jruby/jruby-openssl/commit/adcd03115f6906fad9424f3276b86c9c54f91c05
