### ISSUE TITLE
`OpenSSL::PKey::DH.generate` not implemented

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby-openssl#254]
The `OpenSSL::PKey::DH` class lacks the [`.generate`](https://rubydoc.info/stdlib/openssl/OpenSSL/PKey/DH#generate-class_method) class method. It should simply call `.new` with the key-size and optional "generator" number.

## Steps To Reproduce

```ruby
OpenSSL::PKey::DH.generate(1024)
```

## Expected Result

```ruby
# => #<OpenSSL::PKey::DH:...>
```

## Actual Result

```
NoMethodError (undefined method `generate' for OpenSSL::PKey::DH:Class)
```

## Version

* `jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM 11.0.15+10 on 11.0.15+10 +jit [linux-x86_64]`
* `jruby-openssl (default: 0.11.0 java)`

**Comment by kares** [comment]
https://github.com/jruby/jruby-openssl/commit/adcd03115f6906fad9424f3276b86c9c54f91c05
