### ISSUE TITLE
undefined method `q=' for OpenSSL::PKey::DH

### ISSUE THREAD

**Issue by Unknown-Guy** [jruby/jruby-openssl#300]
Starting with jruby-openssl 0.14.4 sshkit dies with:

```
SSHKit::Runner::ExecuteError: Exception while executing on host staging-app: undefined method `q=' for #<OpenSSL::PKey::DH:0x7cb886f3>
Did you mean?  q
  execute at /Users/user/.rbenv/versions/jruby-9.2.7.0/lib/ruby/gems/shared/gems/sshkit-1.22.2/lib/sshkit/runners/parallel.rb:15
```

0.14.3 works fine.

**Comment by kares** [comment]
Sorry for the inconvenience, we've pushed 0.14.6 with a fix: https://github.com/jruby/jruby-openssl/commit/5f462bdd4438d9e660ec0f8b925889c26eb0aaff 
(please be advised that the `set_pqg` API is deprecated on C-Ruby)
