### ISSUE TITLE
OpenSSL::PKey::EC::Point missing `mul` method

### ISSUE THREAD

**Issue by alextwoods** [jruby/jruby-openssl#306]
It looks like the `OpenSSL::PKey::EC::Point` [class](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/PKeyEC.java#L895) is missing the `mul` method.  It does look like bouncy castle's ECPoint class does support [multiply](https://javadoc.io/doc/org.bouncycastle/bcprov-jdk15on/latest/org/bouncycastle/math/ec/ECPoint.html#multiply-java.math.BigInteger-). 

## Steps to reproduce
```ruby
require 'openssl'
group = OpenSSL::PKey::EC::Group.new('prime256v1')
new_point = group.generator.mul(2)
```

## Expected Result
```
# <OpenSSL::PKey::EC::Point>
```

In cRuby:

```ruby
require 'openssl'
group = OpenSSL::PKey::EC::Group.new('prime256v1')
new_point = group.generator.mul(2) # returns <OpenSSL::PKey::EC::Point:0x000000010dc80218 @group=#<OpenSSL::PKey::EC::Group:0x000000010dc80268>>
```

## Actual result
```
 undefined method `mul' for #<OpenSSL::PKey::EC::Point:0x1f39b3ba> (NoMethodError)
```

## Version
* JRuby: 9.4.5.0
* jruby-openssl: jruby-openssl-0.14.6-java

**Comment by headius** [comment]
Ok less easy since we are not using the BC ECPoint class in this impl. I'm trying to sort it out now.
