### ISSUE TITLE
undefined method `hkdf' for OpenSSL::KDF:Module (NoMethodError)

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby-openssl#312]
When trying to use https://github.com/pushpad/web-push, I get the following error:

    undefined method `hkdf' for OpenSSL::KDF:Module (NoMethodError)
    
 At this line: https://github.com/pushpad/web-push/blob/537267741b8b8cdd4ecedeb3f2da82e1145566d8/lib/web_push/encryption.rb#L29
 
 (there's no stack trace past that)
 
 I'm guessing its just an Openssl 3.x feature that hasn't been implemented yet? Just documenting here, I can always fall back on a previous gem version so not urgent

**Comment by kares** [comment]
closing in favor of https://github.com/jruby/jruby-openssl/issues/321, please do not open multiple issues, instead just update the original if there's more info

**Comment by mohamedhafez** [comment]
whoops sorry! I'd forgotten i'd filed this issue months ago, my mistake! i'll be more careful next time 🙏
