### ISSUE TITLE
Issue with Bouncy-Castle 1.78

### ISSUE THREAD

**Issue by uttam-go** [jruby/jruby-openssl#313]
We are getting this error `OpenSSL::X509::CertificateError: parsing issue: empty extension sequence found` while using latest jruby-openssl 0.15. This issue is present in [Bouncy-Castle 1.78](https://github.com/bcgit/bc-java/issues/1661) and got fixed in latest [Bouncy-Castle 1.78.1](https://www.bouncycastle.org/download/bouncy-castle-java/#:~:text=A%20check%20in%20the%20X.509%20Extensions%20class%20preventing%20the%20parsing%20of%20empty%20extensions%20has%20been%20removed.)

Can we please upgrade to latest  Bouncy-Castle 1.78.1?

**Comment by headius** [comment]
It never ends, does it! 🤦

Yes, of course we will get BC updated and try to put out a 0.15.1 as soon as possible.

**Comment by headius** [comment]
Looks like @kares got to this already in d67cf9a954264abe35c48ec8d745f97000ee1476.
