### ISSUE TITLE
HMAC digest is incorrect when data contains invalid characters

### ISSUE THREAD

**Issue by thedebugger** [jruby/jruby-openssl#33]
```ruby
require 'openssl'

key = "ss"
data = "\xFF"
algo = OpenSSL::Digest::Digest.new("sha256")

digest1 = OpenSSL::HMAC.digest(algo, key, data)

hmac = OpenSSL::HMAC.new(key, algo)
hmac.update(data)
digest2 = hmac.digest

if digest1 == digest2
  p "digests are equal"
else
  p "digests are not equal"
end
```

The reason is ruby string is marshalled to java string when appending data into StringBuilder (https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/HMAC.java#L182)

**Comment by kares** [comment]
@thedebugger thanks!

**Comment by thedebugger** [comment]
@kares Thanks for merging it! After talking to my coworker, he suggested we need a special note (or something like that) when this change goes out since this change would invalidate old HMACs that were generated over the binary data.

**Comment by kares** [comment]
feel free to draft some (short) release notes around your commit [...](https://github.com/jruby/jruby-openssl/blob/master/History.md)
