### ISSUE TITLE
DHE 2048-bit not working on latest JVM7

### ISSUE THREAD

**Issue by mrbrdo** [jruby/jruby-openssl#45]
Latest JVM7 is supposed to support 2048-bit DHE, but it throws "Java::JavaLang::RuntimeException: Could not generate DH keypair".

**Comment by kares** [comment]
thanks, for completeness could you please share your Java version and the work-around you did ...

**Comment by mrbrdo** [comment]
Java version: Oracle 1.7.0_79-b15
Workaround `java.security.Security.setProperty("jdk.tls.disabledAlgorithms", "SSLv3, DHE")`

**Comment by kares** [comment]
we'll be setting it to disabled (just like you did) on Java <= 7 ... on Java 8 we force 1024/2048 DHE for now

**Comment by mrbrdo** [comment]
Doesn't Java 7 support 2048bit DHE?

**Comment by kares** [comment]
@mrbrdo I believe it does not, do you know otherwise?

**Comment by mrbrdo** [comment]
Hm I thought I read that somewhere, but just doing a quick search right now does not reveal any useful info so perhaps you're right.
