### ISSUE TITLE
certs + private keys location is not in line with MRI

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby-openssl#49]
```
/usr/lib/ssl$ ls -al
certs -> /etc/ssl/certs
misc
openssl.cnf -> /etc/ssl/openssl.cnf
private -> /etc/ssl/private
```
MRI seems to inherits this from openssl

currently things do follow this partially:
* for private keys it looks at /usr/lib/ssl/private
* cacerts it looks in $JAVA_HOME/lib/security/cacerts but not in /usr/lib/ssl/certs

ubuntu does link the /usr/lib/ssl/ files to /etc/ssl

so altogether jruby-openssl do use the openssl directories and just fall back on  $JAVA_HOME/lib/security/cacerts if there is a not other cacerts.

**Comment by kares** [comment]
that should be actually smt intended see https://github.com/jruby/jruby-openssl/commit/b914091011bc68d313f6f25a623906057c888874 ... and issues such as https://github.com/jruby/jruby/issues/1953

**Comment by kares** [comment]
reverted in **0.9.10** ... https://github.com/jruby/jruby-openssl/commit/aa35fb94d6fd919229bae18c250751a265f5d5c6

**Comment by mkristian** [comment]
see also discussion on this here: https://github.com/jruby/jruby-openssl/commit/1d3ba21fbe2fc93ff4ff6f7bba3d40396972787c#commitcomment-12800429
