### ISSUE TITLE
What is this gem for?

### ISSUE THREAD

**Issue by jjb** [jruby/jruby-openssl#52]
I've been running JRuby for years and have never used this gem (or maybe I somehow am and don't realize it?). Could someone perhaps add a couple sentences to the Readme explaining what this gem is for?

**Comment by kares** [comment]
> JRuby-OpenSSL is an add-on gem for JRuby that emulates the Ruby OpenSSL native library.

doesn't get any simpler than that ... it's the code behind `require 'openssl'` in JRuby, if you have not used it (directly) do not worry about it ... if its unclear were happy for PRs (even if it's just the README)

**Comment by jjb** [comment]
Sorry I wasn't more clear. I suppose my question is, would it typically be needed when using an http client which accesses sites that use https?

**Comment by jjb** [comment]
My question was inspired by this: https://github.com/librato/librato-metrics/issues/111

Why would that gem believe it was needed when it actually isn't?

**Comment by kares** [comment]
it actually is ... pls do not use github issues for asking questions, there's SO and the mailing list for that

**Comment by jjb** [comment]
Thanks for responding, and I apologize for the low quality of my initial submission. However, I'm fairly certain that a change to the Readme is in order, and I'm trying to figure out what that change should be. It seems something has changed in the JRuby ecosystem and that now this gem is perhaps "built in" to JRuby? Observe here how I don't need it in order to access https resources:

```console
➔ gem uninstall jruby-openssl                           
Successfully uninstalled jruby-openssl-0.9.7-java
➔ rbenv version              
jruby-1.7.20 (set by RBENV_VERSION environment variable)
➔ pry
[1] pry(main)> require "httpclient"
=> true
[2] pry(main)> c = HTTPClient.new; nil
=> nil
[4] pry(main)> c.get("https://www.google.com/").body[0..100]
Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.
Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.
=> "<!doctype html><html itemscope=\"\" itemtype=\"http://schema.org/WebPage\" lang=\"en\"><head><meta content="
```
