### ISSUE TITLE
WaitReadable/Writable exceptions generate backtraces

### ISSUE THREAD

**Issue by headius** [jruby/jruby-openssl#55]
When waiting for the underlying stream to be ready for read or write, SSLSocket causes WaitReadable and WaitWritable versions of SSLError to be raised. These exceptions are generating full backtraces every time, which greatly reduces the performance of these nonblocking IO calls.

I have a small patch that disables the backtraces for Readable, but we'll want to do something configurable and a bit cleaner than this: https://gist.github.com/headius/1900d41e760821fbedf8

It may also be possible to eliminate the need to raise this Ruby error if it is only happening within internal code; specifically, if we are calling into the waitReadable/Writable logic from Java code and capturing the result, there's no reason to raise a full Ruby error.

**Comment by kares** [comment]
looked into this - stumbled across unable to force a `nil` bracktrace: plese review https://github.com/jruby/jruby/pull/3488

**Comment by kares** [comment]
working since 0.9.15 ... also respects `getProperty("jruby.errno.backtrace", "false")`
