### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer

### ISSUE THREAD

**Issue by green-big-frog** [jruby/jruby-openssl#64]
OpenSSL always fails whit specific versions! Or the handshake misses...

Steps to reproduce:
* Install jruby 1.7.19 or 1.7.22 (other versions I didn't test)
* Do a HTTPS call on an API: `jruby -rjson -r'net/http' -e 'p JSON.parse(Net::HTTP.get(URI.parse("https://api.twitch.tv/kraken/streams/kingkongor")))'`
* You should get following error: https://gist.githubusercontent.com/green-big-frog/df545c1858d410a29625/raw/0e67c659d07f7f7097bd3b4a7ae2acdc8c6415e4/jruby-1.7.22.rb

More details can be found here because I tought it might be an API issue: https://discuss.dev.twitch.tv/t/connection-reset-by-peer-always-the-same-but-just-for-me

**Comment by headius** [comment]
FWIW, this works ok on 9k, so it doesn't seem to be a jruby-openssl issue. Will transplant to jruby's issues.

**Comment by green-big-frog** [comment]
Sorry... opened it accidently at the wrong place... Thanks for cleaning up!
