### ISSUE TITLE
WARNING: SSLSocket#session= is not supported

### ISSUE THREAD

**Issue by lolwhitaker** [jruby/jruby-openssl#87]
Hello.  I've seen this WARN log frequently in our builds during the [bundler](https://github.com/bundler/bundler/blob/20f04aa8923c0d0f02e7a74d5e9609d772351668/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb#L67) process as well as when using the [net-http-persistent](https://github.com/drbrain/net-http-persistent/blob/5bae22e8a3626ab3b14743c00796d4f176580ad8/lib/net/http/persistent/ssl_reuse.rb#L67) adapter running jruby 1.7.22.  

```
WARNING: SSLSocket#session= is not supported
```

It looks like this was just [not implemented](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/SSLSocket.java#L1035).  Its pretty annoying, but is it something I should be concerned about?

**Comment by kares** [comment]
something is using `session=` from the **net/http** stack but we can not implement session swapping on Java APIs. it is safe to ignore in this case - we have the method for compat but net/http doesn't care much if it works.

**Comment by lolwhitaker** [comment]
great, thank you for the response.
