### ISSUE TITLE
Proliferation of BouncyCastleProvider instances causing large memory consumption

### ISSUE THREAD

**Issue by bbrowning** [jruby/jruby-openssl#94]
The upgrade to BouncyCastle 1.54 has introduced a bug where we're creating a new BouncyCastleProvider instance for every X509AuxCertificate we create. The code path that leads to this is:
https://github.com/jruby/jruby-openssl/blob/eb200e5341e851545bae5a87ee8c11815e6d62d6/src/main/java/org/jruby/ext/openssl/x509store/X509AuxCertificate.java#L81
which calls
https://github.com/jruby/jruby-openssl/blob/f1ca23c01f5c8f0a94218f36a63f11d8ff269016/src/main/java/org/jruby/ext/openssl/SecurityHelper.java#L194
which ends up creating a new instance of `org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory` that instantiates a new BCJcaJceHelper at
https://github.com/bcgit/bc-java/blob/r1rv54/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/x509/CertificateFactory.java#L40
which ends up returning a new instance of BouncyCastleProvider at
https://github.com/bcgit/bc-java/blob/r1rv54/prov/src/main/java/org/bouncycastle/jcajce/util/BCJcaJceHelper.java#L22 unless the provider is registered already.

This causes the memory consumption of each X509AuxCertificate to explode for me, leading to a baseline memory usage of about 65MB of just BouncyCastleProvider objects in every JRuby runtime. This may be related to #86.

**Comment by bbrowning** [comment]
Steps to reproduce with link to a proposed temporary fix at https://gist.github.com/bbrowning/a6af5239ad35dcdd83212a729d6896c5

**Comment by headius** [comment]
I'm working on a test now.

**Comment by headius** [comment]
I've pulled in @bbrowning's fix but I have been unable to reproduce this locally. We still need a test that confirms the provider stays the same. See my test in 13e964a.

**Comment by kares** [comment]
for the record ... the regression in 1.54 has been (mostly) caused by https://github.com/bcgit/bc-java/commit/4eecbee15751124f47290dafe86f49ca588f73a1

**Comment by kares** [comment]
released jruby-openssl **0.9.17** ... thanks @bbrowning for the investigation and the quick fix.
well also have a test checking that there aren't 2 providers created in place now.
